name: Mosaic CI - Pack

on:
  push:
    branches:
      - master

jobs:
  pack:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/release-candidate'
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
        persist-credentials: false
        ref: master
      
    - name: Install NodeJS
      uses: actions/setup-node@master

    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@master
      env:
        cache-name: mosaic-dependencies
      with:
        path: node_modules
        key: mosaic-dependencies-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: npm ci
    
    - name: Unit Tests
      run: npm run test-coverage
      env:
        CI: true
        
    - name: Generate StoryBook docs
      run: |
        git pull
        npm run build-storybook

    - name: Increase version
      run: npm --no-git-tag-version version patch

    - name: Create RC pull request
      uses: peter-evans/create-pull-request@master
      with:
        commit-message: pre-release ops
        branch: release-candidate
        title: Release Candidate
        body: A new Release Candidate is ready to be submitted
        reviewers: luciobordonaro

      
