name: Mosaic CI - Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@master
      
    - name: Install NodeJS
      uses: actions/setup-node@master

    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@master
      env:
        cache-name: mosaic-dependencies
      with:
        path: node_modules
        key: mosaic-dependencies-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: npm ci
    
    - name: Unit Tests
      run: npm run test-coverage
      env:
        CI: true
